export const GET_RECOMMEND_LIST = 'GET_RECOMMEND_LIST'
export const SET_RECOMMEND_LIST = 'SET_RECOMMEND_LIST'
export const SET_KEYWORDS = 'SET_KEYWORDS'
export const SET_SEARCH_ILLUST = 'SET_SEARCH_ILLUST'
export const CONCAT_SEARCH_ILLUST = 'CONCAT_SEARCH_ILLUST'
export const SET_BOOKMARK = 'SET_BOOKMARK'

